### ISSUE TITLE
Merge setup-flask to develop

### ISSUE THREAD

**Issue by lienharc** [netzbegruenung/candymat#2]
The results of the Hackcamp 08-2019 need to be put together. Create a PR for setup-flask to develop and document the progress made up-til-now.

**Comment by Pit-Storm** [comment]
status of development after hackcamp for backend:
- flask server ready
- README.md ready for development setup on linux and windows+anaconda
- API Routes for: fragen, kandidaten, antwrten, kategorien
- URL request parameter "kat_id" for /fragen should work as aspected.
- tests had been written
